---
- name: Add network interface to a virtual machine (requires the virtual machine's uuid)
  hosts: localhost
  gather_facts: false
  vars_files:
  - group_vars/vars.yaml

  tasks:
    - vmware_guest_network:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ datacenter }}'
        validate_certs: no
        uuid: '{{ uuid }}'
        networks:
        - label: "net_int_2"
          state: new
          name: '{{ network_2 }}'
          connected: true
          start_connected: true
      register: vminfo

    - debug:
        var: vminfo
