---
- name: Gather facts from virtual machine (requires uuid)
  hosts: localhost
  gather_facts: false
  vars_files:
  - group_vars/vars.yaml

  tasks:
    - vmware_guest_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter: '{{ datacenter }}'
        uuid: '{{ uuid }}'
      register: vminfo

    - debug:
        var: vminfo.instance
