---
- name: Upgrade VMWare Tools in LVG with uuid
  hosts: localhost
  gather_facts: false
  vars_files:
  - group_vars/vars.yaml

  tasks:
    - vmware_guest_tools_upgrade:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ datacenter }}'
        uuid: '{{ uuid }}'
        validate_certs: no
      register: vminfo

    - debug:
        var: vminfo
